services:
  react-app:
    build: .
    image: takedaibd-reactjs-app:latest 
    ports:
      - "3000:80"  # Map port 3000 on host to port 80 on the container
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html
      - ./logs:/var/log/nginx/
      - ./config/logrotate.conf:/etc/logrotate.d/nginx
